spring.application.name=leto

spring.datasource.url=jdbc:postgresql://localhost:5432/jira_db
spring.datasource.username=jira_user
spring.datasource.password=Mortal717

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true